library(tidyverse)
nycbikes18_raw <- read_csv("data/2018-citibike-tripdata.csv")
p1 <- ggplot(data = nycbikes18_raw, mapping = aes(fill = usertype, birth_year, nrow(nycbikes18_raw))) + geom_bar(position = "stack", stat = "identity") + labs(y = "count")
nycbikes18 <- filter(nycbikes18_raw, birth_year > 1900)
ttrl_tripd <- sum(nycbikes18[,"tripduration"])
n_bikes <- nrow(unique(nycbikes18[,"bikeid"]))
p2 <- ggplot(data = nycbikes18, mapping = aes(usertype, nrow(nycbikes18))) + geom_bar(stat = "identity") + labs(y = "count")
p3 <- ggplot(data = nycbikes18, aes(x = gender, fill = usertype)) + geom_bar(stat = "count", position = "dodge")
p4 <- ggplot(data = nycbikes18, aes(x = birth_year, y = tripduration)) + geom_point(stat = "identity", size = 0.5) + facet_grid(usertype ~ gender)
p5 <- ggplot(data = nycbikes18, aes(x = start_station_longitude, y = start_station_latitude)) + geom_point() + geom_point(aes(x = end_station_longitude, y = end_station_latitude))
p6 <- ggplot(data = nycbikes18, aes(x = start_station_longitude, xend = end_station_longitude, y = start_station_latitude, yend = end_station_latitude)) + geom_segment(arrow = arrow(length = unit(0.01, 'npc')), alpha = 0.3)
